---
#  - name: This will download tomcat9
#    get_url:
#      url:  http://www.gtlib.gatech.edu/pub/apache/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13-deployer.zip
#      dest: /opt/test
#      mode: 0770
#
  - name: This will run CentOs7 system patches
    yum:
      name: '*'
      state:  latest
    tags: skip_update
