---
  - name: Create tomcat9 directory
    file:
      path: /opt/tomcat9
      state:  directory
    tags: skip_cdirectory

  - name: Download current release of tomcat9
    get_url:
      url:  http://apache.mirrors.ionfish.org/tomcat/tomcat-9/v9.0.13/bin/apache-tomcat-9.0.13.tar.gz
      dest: /opt/
    tags: skip_download

  - name: Extract tomcat tar.zip file
    unarchive:
      src: /opt/apache-tomcat-9.0.13.tar.gz
      dest: /opt/tomcat9/
      remote_src: yes
    tags: skip_unarchive

#  - name: Move extracted directory to Tomcat9 Directory
#    command: mv /opt/tomcat9/apache-tomcat-9.0.13 /opt/tomcat9/tomcat
#    tags: skip_copy

  - name:  This will install OpenJDK 8 JRE
    yum:
      name: java-1.8.0-openjdk
      state:  present
    tags: skip_jre

  - name: This will install OpenJDK 8 JDK
    yum:
      name: java-1.8.0-openjdk-devel
      state:  present
    tags: skip_jdk

  - name: This will run CentOs7 system updates
    yum:
      name: '*'
      state:  latest
    tags: skip_update
