---
  - name: This will download tomcat9
    get_url:
      url:  http://archive.apache.org/dist/tomcat/tomcat-9/v9.0.0.M26/bin/apache-tomcat-9.0.0.M26-windows-x64.zip 
      dest: /opt/test
      mode: 0770
